import type { ToolMeta } from "@/types";

export const meta: ToolMeta = {
  slug: "color-picker",
  name: "Color Picker",
  tagline: "Pick, explore, and copy colors in any format",
  description:
    "Free online color picker tool. Select any color and instantly get HEX, RGB, HSL, and HSB values. Generate color shades and copy with one click.",
  category: "color",
  keywords: [
    "color picker",
    "color picker online",
    "hex color picker",
    "rgb color picker",
    "color code picker",
    "hsl color picker",
  ],
  faqs: [
    {
      question: "What is a color picker?",
      answer:
        "A color picker is a tool that lets you visually select a color and get its corresponding code in formats like HEX, RGB, or HSL, which you can use in CSS, design tools, or any application that accepts color values.",
    },
    {
      question: "What is the difference between HEX, RGB, and HSL?",
      answer:
        "HEX is a hexadecimal representation (#ff5733). RGB uses red, green, blue values (0-255). HSL uses hue (0-360°), saturation (0-100%), and lightness (0-100%). All describe the same colors but in different formats used in different contexts.",
    },
    {
      question: "How do I copy a color code?",
      answer:
        "Click on any color value (HEX, RGB, HSL) and it will be automatically copied to your clipboard. A checkmark will confirm the copy was successful.",
    },
    {
      question: "Can I input a specific HEX or RGB value?",
      answer:
        "Yes! You can type any valid HEX code (e.g., #6366f1) or RGB value directly into the input fields, and the color picker will update to show that color.",
    },
    {
      question: "What are color shades and how are they generated?",
      answer:
        "Color shades are lighter and darker variations of a base color. They are generated by adjusting the lightness value in HSL space while keeping the hue and saturation constant, creating a harmonious palette.",
    },
    {
      question: "Is this color picker free to use?",
      answer:
        "Yes, this color picker is completely free with no sign-up required. All processing happens in your browser.",
    },
  ],
  relatedTools: [
    "color-converter",
    "password-generator",
    "uuid-generator",
    "base64",
  ],
  howToSteps: [
    "Click or drag the color spectrum to pick a color",
    "Fine-tune hue, saturation, and lightness with the sliders",
    "View the color code in HEX, RGB, and HSL formats",
    "Click any value to copy it to your clipboard",
    "Explore the generated color shades below",
  ],
  lastUpdated: "2025-01-01",
};
